# ArtaCast finishing pipeline — generated by ArtaQuest for request {{REQUEST_ID}}.
#
# Takes the episode the host's browser recorded (video untouched), cleans the voices with the best
# open speech-enhancement model the box can run, normalises loudness to YouTube's target, and writes
# a release-ready file beside the thumbnail and a report. Every stage is guarded: whatever fails,
# there is always an output, and the report says which model actually ran.
#
#   raw video ──► audio 48 kHz ──► enhance (MossFormer2_SE_48K → noisereduce → afftdn)
#             ──► loudnorm two-pass (−14 LUFS, −1 dBTP, LRA 11) ──► mux (video copied) ──► outputs
import os, sys, json, subprocess, time, shutil, glob, re, math

RAW_URL    = "{{RAW_URL}}"
THUMB_URL  = "{{THUMB_URL}}"
OUT_BASE   = "{{OUT_BASE}}"
REQUEST_ID = "{{REQUEST_ID}}"

WORK = "/kaggle/working"
TMP  = "/kaggle/tmp/artacast"
os.makedirs(TMP, exist_ok=True)
os.makedirs(WORK, exist_ok=True)
T0 = time.time()
report = {"request": REQUEST_ID, "steps": [], "model": "", "lufs_before": None, "lufs_after": None, "outputs": []}

def step(name, ok, **kw):
    report["steps"].append({"step": name, "ok": bool(ok), "t": round(time.time() - T0, 1), **kw})
    print(f"[{time.time()-T0:7.1f}s] {name}: {'ok' if ok else 'FAIL'} {json.dumps(kw, default=str)[:400]}", flush=True)

def sh(cmd, check=True, timeout=None):
    r = subprocess.run(cmd, shell=isinstance(cmd, str), capture_output=True, text=True, timeout=timeout)
    if check and r.returncode != 0:
        raise RuntimeError(f"{cmd if isinstance(cmd, str) else ' '.join(cmd)}\n{r.stderr[-2000:]}")
    return r

def ffmpeg_bin():
    for name in ("ffmpeg",):
        p = shutil.which(name)
        if p: return p
    try:
        import imageio_ffmpeg
    except ImportError:
        sh([sys.executable, "-m", "pip", "install", "-q", "imageio-ffmpeg"], check=False, timeout=600)
        import imageio_ffmpeg
    return imageio_ffmpeg.get_ffmpeg_exe()

FF = ffmpeg_bin()
FFPROBE = shutil.which("ffprobe") or ""

def probe(path):
    if FFPROBE:
        r = sh([FFPROBE, "-v", "error", "-print_format", "json", "-show_streams", "-show_format", path], check=False)
        try:
            j = json.loads(r.stdout or "{}")
            streams = j.get("streams", [])
            return {
                "duration": float(j.get("format", {}).get("duration", 0) or 0),
                "video": next((s for s in streams if s.get("codec_type") == "video"), None),
                "audio": next((s for s in streams if s.get("codec_type") == "audio"), None),
            }
        except Exception:
            pass
    # ffmpeg-only fallback: parse "Duration:"
    r = sh([FF, "-i", path], check=False)
    m = re.search(r"Duration: (\d+):(\d+):([\d.]+)", r.stderr)
    dur = (int(m[1]) * 3600 + int(m[2]) * 60 + float(m[3])) if m else 0.0
    return {"duration": dur, "video": {"codec_name": "?"} if "Video:" in r.stderr else None, "audio": {} if "Audio:" in r.stderr else None}

# ── 1. the raw recording ────────────────────────────────────────────────────────────────────────
def download(url, dest, tries=6):
    import urllib.request
    have = os.path.getsize(dest) if os.path.exists(dest) else 0
    for i in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "ArtaCast-finish/1", **({"Range": f"bytes={have}-"} if have else {})})
            with urllib.request.urlopen(req, timeout=120) as r, open(dest, "ab" if have else "wb") as f:
                if have and r.status != 206:
                    f.close(); open(dest, "wb").close(); have = 0
                    f = open(dest, "wb")
                while True:
                    b = r.read(1 << 22)
                    if not b: break
                    f.write(b); have += len(b)
            return dest
        except Exception as e:
            print(f"download try {i+1}: {e}", flush=True)
            have = os.path.getsize(dest) if os.path.exists(dest) else 0
            time.sleep(5 * (i + 1))
    raise RuntimeError("could not download the recording")

raw = ""
try:
    if RAW_URL.startswith("http"):
        ext = os.path.splitext(RAW_URL.split("?")[0])[1].lower() or ".mp4"
        raw = download(RAW_URL, os.path.join(TMP, "raw" + ext))
    else:
        cands = [p for p in glob.glob("/kaggle/input/**/*", recursive=True) if p.lower().endswith((".mp4", ".webm", ".mov", ".m4v", ".mkv"))]
        if not cands: raise RuntimeError("no recording attached")
        raw = max(cands, key=os.path.getsize)
    info = probe(raw)
    step("raw", True, path=os.path.basename(raw), bytes=os.path.getsize(raw), duration=round(info["duration"], 1),
         video=(info["video"] or {}).get("codec_name"), audio=bool(info["audio"]))
except Exception as e:
    step("raw", False, error=str(e)[:500])
    json.dump(report, open(os.path.join(WORK, OUT_BASE + "-report.json"), "w"), indent=1)
    print("ARTACAST_FAILED raw", flush=True)
    sys.exit(0)

raw_ext = os.path.splitext(raw)[1].lower()
has_video = bool(info["video"])
duration = info["duration"]

# ── 2. the voices, alone ─────────────────────────────────────────────────────────────────────────
IN_WAV = os.path.join(TMP, "in.wav")
sh([FF, "-y", "-i", raw, "-vn", "-ac", "1", "-ar", "48000", "-c:a", "pcm_s16le", IN_WAV])
step("extract", True, seconds=round(probe(IN_WAV)["duration"], 1))

def lufs(path):
    r = sh([FF, "-i", path, "-af", "ebur128=peak=true", "-f", "null", "-"], check=False)
    m = re.findall(r"I:\s+(-?[\d.]+) LUFS", r.stderr)
    return float(m[-1]) if m else None
report["lufs_before"] = lufs(IN_WAV)
step("measure", True, lufs=report["lufs_before"])

# ── 3. enhance ───────────────────────────────────────────────────────────────────────────────────
ENH_WAV = os.path.join(TMP, "enh.wav")

model = ""
print("python", sys.version.split()[0], flush=True)

# Each model runs in a FRESH interpreter: its pip installs (numpy 2 for ClearerVoice, say) must not
# fight the packages this process already imported, and a model that segfaults must not take the
# pipeline with it. The runner reads IN_WAV, writes ENH_WAV, prints MODEL=<name> on success.
RUNNER = r'''
import sys, os, subprocess, json
IN_WAV, ENH_WAV, TMP, WHICH = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
def pip(*pk):
    r = subprocess.run([sys.executable, "-m", "pip", "install", "-q", *pk], capture_output=True, text=True, timeout=1500)
    if r.returncode != 0:
        raise RuntimeError("pip " + " ".join(pk) + " failed:\n" + (r.stdout + r.stderr)[-1200:])
if WHICH == "mossformer2":
    try:
        from clearvoice import ClearVoice
    except Exception:
        # --no-deps on purpose: clearvoice pins numpy<2 while Kaggle ships numpy 2 with a torch built
        # against it; letting pip "fix" that downgrades numpy under every compiled package on the
        # box. Its real needs are small pure-python packages; the heavy ones are already installed.
        pip("--no-deps", "clearvoice")
        pip("einops", "gdown", "rotary_embedding_torch", "yamlargparse", "python_speech_features", "torchinfo", "pydub", "huggingface-hub>=0.26.2")
        from clearvoice import ClearVoice
    import numpy as np, soundfile as sf, torch
    print("torch", torch.__version__, "numpy", np.__version__, "cuda", torch.cuda.is_available(), flush=True)
    cv = ClearVoice(task="speech_enhancement", model_names=["MossFormer2_SE_48K"])
    SR = 48000
    def process(seg):
        p = os.path.join(TMP, "seg.wav"); sf.write(p, seg, SR, subtype="PCM_16")
        y = cv(input_path=p, online_write=False)
        if isinstance(y, dict): y = next(iter(y.values()))
        y = np.asarray(y, dtype=np.float32)
        return y.reshape(-1) if y.ndim == 1 else y[0].reshape(-1)
    NAME = "MossFormer2_SE_48K (ClearerVoice-Studio)"
elif WHICH == "deepfilternet":
    try:
        from df.enhance import enhance, init_df
    except Exception:
        pip("deepfilternet")
        from df.enhance import enhance, init_df
    import numpy as np, soundfile as sf, torch
    dfm, dfs, _ = init_df()
    SR = dfs.sr()
    def process(seg):
        t = torch.from_numpy(np.asarray(seg, dtype=np.float32)).unsqueeze(0)
        return enhance(dfm, dfs, t).squeeze(0).detach().cpu().numpy()
    NAME = "DeepFilterNet3"
elif WHICH == "noisereduce":
    try:
        import noisereduce as nr
    except Exception:
        pip("noisereduce")
        import noisereduce as nr
    import numpy as np, soundfile as sf
    SR = 48000
    def process(seg):
        return nr.reduce_noise(y=np.asarray(seg, dtype=np.float32), sr=SR, stationary=False, prop_decrease=0.85)
    NAME = "noisereduce (spectral gating)"
else:
    raise SystemExit("unknown model")

import numpy as np, soundfile as sf
x, xsr = sf.read(IN_WAV, dtype="float32", always_2d=False)
if xsr != SR:
    import subprocess as sp
    tmp = os.path.join(TMP, f"in{SR}.wav")
    sp.run(["ffmpeg", "-y", "-loglevel", "error", "-i", IN_WAV, "-ac", "1", "-ar", str(SR), "-c:a", "pcm_s16le", tmp], check=True)
    x, xsr = sf.read(tmp, dtype="float32", always_2d=False)
n = len(x); c = int(45.0 * SR); o = int(1.0 * SR)
out = np.zeros(n, dtype=np.float32); wsum = np.zeros(n, dtype=np.float32)
ramp = np.linspace(0, 1, o, dtype=np.float32)
start = 0; k = 0
while start < n:
    end = min(n, start + c); seg = x[start:end]
    y = np.asarray(process(seg), dtype=np.float32).reshape(-1)
    if len(y) != len(seg):
        y = np.interp(np.linspace(0, len(y) - 1, len(seg)), np.arange(len(y)), y).astype(np.float32) if len(y) > 1 else np.zeros(len(seg), np.float32)
    w = np.ones(len(seg), dtype=np.float32)
    if start > 0 and len(seg) >= o: w[:o] = ramp
    if end < n and len(seg) >= o: w[-o:] = ramp[::-1]
    out[start:end] += y * w; wsum[start:end] += w
    k += 1
    if k % 10 == 0: print(f"  chunk {k}, {end/SR/60:.1f} min", flush=True)
    start = end - o if end < n else n
out = out / np.maximum(wsum, 1e-6)
peak = float(np.max(np.abs(out))) if n else 0.0
if peak > 0.99: out = out * (0.99 / peak)
sf.write(ENH_WAV, out, SR, subtype="PCM_16")
print("MODEL=" + NAME, flush=True)
'''
runner_path = os.path.join(TMP, "runner.py")
open(runner_path, "w").write(RUNNER)

for which in ("mossformer2", "noisereduce"):
    if model: break
    try:
        # cwd=TMP: a model that downloads its checkpoints into the working directory must not leave them
        # among the outputs (ClearerVoice writes ./checkpoints/).
        r = subprocess.run([sys.executable, runner_path, IN_WAV, ENH_WAV, TMP, which], capture_output=True, text=True, timeout=4 * 3600, cwd=TMP)
        tail = (r.stdout + r.stderr)[-1500:]
        m = re.search(r"MODEL=(.+)", r.stdout)
        if r.returncode == 0 and m and os.path.exists(ENH_WAV) and os.path.getsize(ENH_WAV) > 1000:
            model = m.group(1).strip()
            step("enhance", True, model=model, log=r.stdout[-300:])
        else:
            step("enhance-" + which, False, error=tail[-700:])
    except Exception as e:
        step("enhance-" + which, False, error=str(e)[-600:])

# A model that shortened or stretched the file is worse than no model.
try:
    d_in, d_out = probe(IN_WAV)["duration"], probe(ENH_WAV)["duration"]
    if d_in > 0 and abs(d_out - d_in) > max(0.5, 0.01 * d_in):
        step("enhance-check", False, in_s=d_in, out_s=d_out, note="length drifted — using the raw voices")
        shutil.copy(IN_WAV, ENH_WAV); model = "none (length drift)"
    else:
        step("enhance-check", True, in_s=round(d_in, 1), out_s=round(d_out, 1))
except Exception as e:
    step("enhance-check", False, error=str(e)[:300])
report["model"] = model

# ── 4. loudness — YouTube's target, two-pass so it is a measurement, not a guess ─────────────────
NORM_WAV = os.path.join(TMP, "norm.wav")
TARGET = "loudnorm=I=-14:TP=-1.0:LRA=11"
try:
    r = sh([FF, "-i", ENH_WAV, "-af", f"highpass=f=60,{TARGET}:print_format=json", "-f", "null", "-"], check=False)
    m = re.search(r"\{[^{}]*\"input_i\"[^{}]*\}", r.stderr, re.S)
    meas = json.loads(m.group(0)) if m else {}
    if meas:
        second = (f"highpass=f=60,{TARGET}:measured_I={meas['input_i']}:measured_TP={meas['input_tp']}:measured_LRA={meas['input_lra']}"
                  f":measured_thresh={meas['input_thresh']}:offset={meas['target_offset']}:linear=true:print_format=summary")
    else:
        second = f"highpass=f=60,{TARGET}"
    sh([FF, "-y", "-i", ENH_WAV, "-af", second, "-ar", "48000", "-c:a", "pcm_s16le", NORM_WAV])
    report["lufs_after"] = lufs(NORM_WAV)
    step("loudnorm", True, measured=meas.get("input_i"), lufs_after=report["lufs_after"])
except Exception as e:
    step("loudnorm", False, error=str(e)[-500:])
    shutil.copy(ENH_WAV, NORM_WAV)

# ── 5. back into the picture ─────────────────────────────────────────────────────────────────────
out_path = ""
try:
    if has_video:
        if raw_ext == ".webm":
            out_path = os.path.join(WORK, OUT_BASE + ".webm")
            sh([FF, "-y", "-i", raw, "-i", NORM_WAV, "-map", "0:v:0", "-map", "1:a:0", "-c:v", "copy", "-c:a", "libopus", "-b:a", "192k", "-shortest", out_path])
        else:
            out_path = os.path.join(WORK, OUT_BASE + ".mp4")
            sh([FF, "-y", "-i", raw, "-i", NORM_WAV, "-map", "0:v:0", "-map", "1:a:0", "-c:v", "copy", "-c:a", "aac", "-b:a", "256k", "-ar", "48000", "-movflags", "+faststart", "-shortest", out_path])
    else:
        out_path = os.path.join(WORK, OUT_BASE + ".m4a")
        sh([FF, "-y", "-i", NORM_WAV, "-c:a", "aac", "-b:a", "256k", "-ar", "48000", "-movflags", "+faststart", out_path])
    o = probe(out_path)
    ok = os.path.getsize(out_path) > 0 and (not has_video or o["video"]) and o["audio"] and abs(o["duration"] - duration) < max(2.0, 0.02 * duration)
    step("mux", bool(ok), out=os.path.basename(out_path), bytes=os.path.getsize(out_path), duration=round(o["duration"], 1))
    if not ok: raise RuntimeError("the muxed file does not check out")
except Exception as e:
    step("mux", False, error=str(e)[-500:])
    # The one thing that must never happen is an empty result: ship the raw with normalised audio
    # re-encoded, or at the very worst the raw itself.
    try:
        out_path = os.path.join(WORK, OUT_BASE + "-fallback.mp4")
        sh([FF, "-y", "-i", raw, "-i", NORM_WAV, "-map", "0:v:0?", "-map", "1:a:0", "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-c:a", "aac", "-b:a", "256k", "-movflags", "+faststart", "-shortest", out_path])
        step("mux-fallback", True, out=os.path.basename(out_path))
    except Exception as e2:
        step("mux-fallback", False, error=str(e2)[-300:])
        out_path = os.path.join(WORK, OUT_BASE + "-raw" + raw_ext); shutil.copy(raw, out_path)

# ── 6. the thumbnail and the report ──────────────────────────────────────────────────────────────
if THUMB_URL.startswith("http"):
    try:
        download(THUMB_URL, os.path.join(WORK, OUT_BASE + "-thumbnail.png"))
        step("thumbnail", True)
    except Exception as e:
        step("thumbnail", False, error=str(e)[:200])

for stray in ("checkpoints", "outputs", "__pycache__"):
    shutil.rmtree(os.path.join(WORK, stray), ignore_errors=True)
report["outputs"] = sorted(os.path.basename(p) for p in glob.glob(os.path.join(WORK, "*")) if os.path.isfile(p))
report["seconds"] = round(time.time() - T0, 1)
json.dump(report, open(os.path.join(WORK, OUT_BASE + "-report.json"), "w"), indent=1)
shutil.rmtree(TMP, ignore_errors=True)
print("ARTACAST_DONE " + json.dumps({"model": model, "lufs_before": report["lufs_before"], "lufs_after": report["lufs_after"], "outputs": report["outputs"]}), flush=True)
