/**
 * The JupyterBook page — every work's notebook, read as a book.
 *
 * Operator order (2026-07-29): *"every content must have its jupyterbook page that is generated by
 * the submitted kaggle notebook"* and *"ArtaReader embedded inside"*. Those two sentences together
 * decide the build. A literal `jupyter-book` static site would be an opaque iframe, and nothing of
 * ArtaReader could live inside it — so the book is generated in the browser from the submitted
 * `.ipynb` (`lib/ipynb.ts`) and handed straight to `ReadMode`, which IS ArtaReader. The member gets
 * its typography controls, contents panel, remembered reading position, themes, fullscreen and
 * narration over the notebook itself.
 *
 * It has its OWN URL (`/nb/<id>/book`, and the slugged form) rather than being a modal on the work
 * page, because "every content must have its page" means linkable and shareable, not a state flag.
 *
 * **Credit.** Any member may submit any public kernel, so the book is credited to the notebook's
 * KAGGLE author — never the submitter — matching the DOI, the BibTeX and the work page. When the
 * two differ the byline says so rather than quietly picking one.
 *
 * **Figures.** ReadMode's figures panel carries the artifacts the run actually produced (the
 * published files, already mirrored to our CDN), plus any images the notebook carried in its own
 * outputs. Kaggle's `kernels/pull` strips outputs, so in practice the panel is the published files
 * — which is the honest thing to show anyway: those files ARE the result.
 */
import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getNotebook, type NotebookFull } from "../lib/api";
import { ReadMode, type ReaderDoc } from "../components/reader";
import { LibraryMedia, foldScene } from "../components/library";
import { notebookToBook, bookSummary } from "../lib/ipynb";
import { ipynbHref, kaggleRunHref, labRunUrl } from "../lib/pykernel";
import { watchMath } from "../lib/math";
import { Button, EmptyState, OrbitRings, StatusNote } from "../components/ui";

export default function NotebookBook() {
  const { id, slug } = useParams();
  const navigate = useNavigate();
  const [nb, setNb] = useState<NotebookFull | null>(null);
  const [missing, setMissing] = useState(false);

  useEffect(() => {
    setNb(null); setMissing(false);
    getNotebook(Number(id)).then(setNb).catch(() => setMissing(true));
  }, [id]);

  const book = useMemo(() => (nb ? notebookToBook(nb.ipynb) : null), [nb]);

  useEffect(() => {
    if (!nb) return;
    document.title = `${nb.title} — read the notebook · ArtaQuest`;
  }, [nb]);

  // The prose can carry LaTeX. renderRich has ALREADY turned `$…$` into .aq-math[data-tex] nodes,
  // so this is the "nodes" pass — "auto" would rescan raw text that no longer contains any maths,
  // and would also treat a bare price in the notebook's prose as an equation.
  useEffect(() => {
    if (!book) return;
    return watchMath(document.body, "nodes");
  }, [book]);

  const workHref = `/nb/${nb?.id ?? id}${slug ? `/${slug}` : ""}`;

  const doc: ReaderDoc | null = useMemo(() => {
    if (!nb) return null;
    const kaggleAuthor = nb.kaggle?.author || nb.kaggle?.owner || "";
    return {
      id: nb.id,
      title: nb.title,
      // The Kaggle author is the author. Only fall back to the submitting member when the kernel
      // block is missing entirely (pre-reset rows), never as a preference.
      author: kaggleAuthor ? { name: kaggleAuthor } : { name: nb.author.name, slug: nb.author.slug },
      created: nb.created,
      abstract: nb.abstract || "",
      // NOT nb.doi_link. ReadMode renders `https://doi.org/${s.doi}`, but doi_link is already a full
      // URL (Doi::nb_link → https://artaquest.com/d/n45), so it produced
      // https://doi.org/https://artaquest.com/d/n45 — a 404 — and printed "doi.org" on the page,
      // which the platform's own rule forbids: member-facing citations show ONLY /d/n<id> and never
      // name the archive provider. The citation lives on the work page, one control away.
      doi: "",
      eyebrow: "ArtaQuest · Notebook",
      license: "CC BY 4.0",
      lang: "en",
      dir: "auto",
      posNs: "nb",
    };
  }, [nb]);

  if (missing) {
    return (
      <div className="mx-auto max-w-2xl py-16">
        <EmptyState title="No such work" body="This notebook has been removed, or the link is wrong." />
        <div className="mt-4 text-center"><Button href="/works/">Back to the feed</Button></div>
      </div>
    );
  }
  if (!nb || !doc) {
    return <div className="grid place-items-center py-24"><OrbitRings className="h-10 w-10" /></div>;
  }

  if (!book) {
    return (
      <div className="mx-auto max-w-2xl space-y-4 py-16">
        <StatusNote>
          This work has no readable notebook yet — its source has not been pulled from Kaggle, so
          there is nothing to lay out as a book.
        </StatusNote>
        <div className="text-center"><Button href={workHref}>Open the work</Button></div>
      </div>
    );
  }

  // A SCENE work's three files are ONE figure: the animated vector, with its raster twin and its
  // poster as the fallbacks SceneMedia picks between (never a second and third copy of the same
  // picture, two of them moving).
  const files = nb.files || [];
  const figs = foldScene(files);
  const hasFigures = figs.length > 0 || book.images.length > 0;

  const figures = hasFigures ? (
    <div className="space-y-6">
      {figs.map((f) => (
        <figure key={f.id} className="space-y-2">
          <LibraryMedia item={f} files={files} />
          <figcaption className="text-[13px] text-ink-3">
            <span data-ay-skip="1">{f.label || f.name}</span>
          </figcaption>
        </figure>
      ))}
      {book.images.map((im, i) => (
        <figure key={`emb-${i}`} className="space-y-2">
          <img src={im.src} alt={im.alt} loading="lazy" className="max-w-full rounded-card border border-line" />
          <figcaption className="text-[13px] text-ink-3">
            <span data-ay-skip="1">{im.alt}</span>
          </figcaption>
        </figure>
      ))}
    </div>
  ) : undefined;

  // REPRODUCE IT, FROM THE PAGE YOU READ IT ON (operator 2026-07-29). A reader who has just read
  // the notebook is exactly the person who wants to run it, and making them navigate back to the
  // work page to find that button loses most of them. Both routes are real:
  //   · in browser — /lab, Pyodide in a worker, cell by cell, streaming output (lib/pykernel.ts)
  //   · on Kaggle  — the kernel's own /edit, which is where Copy & Edit lands, so it runs on the
  //                  same public inputs the checklist verified. Anonymous visitors bounce to the
  //                  kernel page, which is the honest outcome rather than a broken one.
  // The .ipynb download is the third, offline route — the file this book was generated from.
  const kaggleRun = kaggleRunHref(nb.kaggle?.url || nb.kaggle_url || "");
  // ≤640px the reader bar is `flex-wrap: nowrap; overflow: hidden` and its width budget was tuned to
  // just fit the existing controls, so anything appended is clipped off-screen with no way to scroll
  // to it. All the run controls therefore carry aq-read-hide-sm and only "The work" survives on a
  // phone — which is the right one to keep, because the full three-tier ladder lives on that page.
  const actions = (
    <>
      <a className="aq-read-ctl aq-read-hide-sm" href={labRunUrl(nb.id, nb.slug)} title="Runs here, in this tab — no account, nothing leaves your device">
        <svg viewBox="0 0 24 24" width="14" height="14" fill="currentColor" aria-hidden><path d="M8 5v14l11-7z" /></svg>
        <span className="aq-read-label">Run in browser</span>
      </a>
      {/* Tier 2. A gist-backed Colab link is a plain anchor; without one the rung saves the file and
          opens Colab, because Colab has no open-by-URL form. */}
      {(nb.colab_url || "").startsWith("https://colab.research.google.com/") ? (
        <a className="aq-read-ctl aq-read-hide-sm" href={nb.colab_url} target="_blank" rel="noopener noreferrer"
           title="Tier 2 — the heavy one: opens straight in Colab, for a GPU and large installs">
          <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M14 4h6v6M20 4l-9 9M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5" /></svg>
          <span className="aq-read-label">Colab</span>
        </a>
      ) : (
      <a className="aq-read-ctl aq-read-hide-sm" href={ipynbHref(nb.id, nb.slug)} download={`${nb.slug || "notebook"}.ipynb`}
         title="Tier 2 — the heavy one: save the notebook, then drop it into Colab for a GPU"
         onClick={() => { window.setTimeout(() => window.open("https://colab.research.google.com/#create=true", "_blank", "noopener,noreferrer"), 300); }}>
        <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M12 3v12M7 10l5 5 5-5M4 19h16" /></svg>
        <span className="aq-read-label">Colab</span>
      </a>
      )}
      {kaggleRun !== "" && (
        <a className="aq-read-ctl aq-read-hide-sm" href={kaggleRun} target="_blank" rel="noopener noreferrer"
           title="Copy &amp; Edit on Kaggle, then Run All — the same public inputs the checklist read">
          <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M14 4h6v6M20 4l-9 9M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5" /></svg>
          <span className="aq-read-label">Run on Kaggle</span>
        </a>
      )}
      <a className="aq-read-ctl aq-read-hide-sm" href={ipynbHref(nb.id, nb.slug)}
         download={`${nb.slug || "notebook"}.ipynb`} title="The exact notebook this book was generated from">
        <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M12 3v12M7 10l5 5 5-5M4 19h16" /></svg>
        <span className="aq-read-label">.ipynb</span>
      </a>
      <a className="aq-read-ctl" href={workHref} title="The work page: the reproducibility checklist, the files, the discussion">
        <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M4 6h16M4 12h16M4 18h10" /></svg>
        <span className="aq-read-label">The work</span>
      </a>
    </>
  );

  return (
    <>
      {/* The one line that says what this book is made of, before the reader takes the screen. */}
      <p className="sr-only" data-ay-skip="1">{bookSummary(book)}</p>
      <ReadMode
        s={doc}
        body={book.html}
        figures={figures}
        hasFigures={hasFigures}
        actions={actions}
        onClose={() => navigate(workHref)}
        // Closing navigates to the work page, so there is nothing on THIS page to hand focus back to.
        returnFocus={() => {}}
      />
    </>
  );
}
