/**
 * The notebook, as a book.
 *
 * Operator order (2026-07-29): *"every content must have its jupyterbook page that is generated by
 * the submitted kaggle notebook"*, with *"ArtaReader embedded inside"*. This module is the
 * generator. It turns the submitted `.ipynb` into the one HTML string `ReadMode` reads, so the
 * JupyterBook page is not a lookalike of the reader — it IS the reader, with its typography
 * controls, contents panel, reading position, themes and narration.
 *
 * **What can and cannot be shown, established by probing Kaggle rather than reading their docs.**
 * `kernels/pull` returns the notebook SOURCE with `outputs: []` on every cell (verified on two live
 * public kernels), and `kernels/output` lists only the files the notebook wrote — never
 * `__results__.html` (checked across all 1,322 output files of one kernel and the 2 of another). So
 * Kaggle's own executed render is not retrievable, and a page claiming to show "the run" from the
 * pulled source would be showing something no run produced.
 *
 * The honest construction, which is also the platform's claim: **the notebook as its author wrote
 * it, beside the artifacts the run actually produced.** Narrative and code come from here; the
 * outputs come from the published files, handed to `ReadMode` as its `figures` panel. If a notebook
 * does carry embedded outputs (a locally authored one might) they render too — that path exists and
 * simply never fires for a Kaggle pull.
 *
 * ## Why this emits HTML, and why code never goes through the markdown renderer
 *
 * `ReadMode` takes `body` as **HTML** and injects it with `dangerouslySetInnerHTML` (deliberately —
 * replacing text nodes is what lets ArtaTTS follow sentences). Everything here is therefore
 * security-critical: a notebook is member-authored, and Jupyter markdown routinely contains raw
 * HTML.
 *
 *   - **Prose** goes through `renderRich()`, the platform's XSS-safe markdown renderer: it escapes
 *     every run of text *before* emitting any tag, so nothing an author writes can inject markup.
 *     Raw HTML in a markdown cell therefore renders as visible literal text — the safe failure.
 *   - **Code is never passed to it.** `renderRich` recognises only three-backtick fences and drops
 *     the language, so a cell containing a fence of its own (a notebook that prints markdown — not
 *     exotic) would break out and be re-parsed as prose. Code blocks are escaped and wrapped here
 *     instead, which also keeps the language label.
 *
 * Everything is pure and synchronous: no fetch, no DOM. The book stays generatable offline from a
 * cached work, and is testable as a plain function.
 */
import { renderRich } from "./wp";

/** An image carried inside the notebook's own outputs. Empty for a Kaggle pull. */
export type BookImage = { src: string; alt: string; step: number };

export type NotebookBook = {
  /** The HTML `ReadMode` renders. */
  html: string;
  /** Notebook language, lowercased — labelled on each code block. */
  lang: string;
  cells: number;
  codeCells: number;
  mdCells: number;
  /** Headings found in the AUTHOR'S markdown. Zero means the structure had to be synthesised. */
  authorHeadings: number;
  images: BookImage[];
};

/** nbformat lets `source`, and every output text field, be a string OR an array of lines. */
function joinSource(v: unknown): string {
  if (typeof v === "string") return v;
  if (Array.isArray(v)) return v.map((x) => (typeof x === "string" ? x : "")).join("");
  return "";
}

function tidy(s: string): string {
  return s.replace(/\s+$/, "");
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/** Heading text → anchor id. Any stable mapping works: ReadMode's contents panel reads the ids back
 *  out of this very HTML, so the two cannot drift apart the way a separately-derived TOC would. */
function slug(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "section";
}

/** Count ATX headings in markdown, ignoring anything inside a fence (`# comment` is Python, not H1). */
function countHeadings(md: string): number {
  let n = 0;
  let inFence = false;
  for (const line of md.split("\n")) {
    if (/^\s*`{3,}/.test(line)) { inFence = !inFence; continue; }
    if (!inFence && /^#{1,6}\s+\S/.test(line)) n++;
  }
  return n;
}

/**
 * Give every h1–h3 a unique id, so ReadMode's contents panel (which scans for `<h2 id>`/`<h3 id>`)
 * has something to list. `renderRich` emits headings without ids — it was written for discussion
 * bodies, which have no contents panel — and changing it would touch every comment on the platform.
 */
function uniqueId(base: string, used: Set<string>): string {
  let id = base;
  for (let i = 2; used.has(id); i++) id = `${base}-${i}`;
  used.add(id);
  return id;
}

/**
 * Give every heading an id — and DEMOTE h1 to h2 on the way.
 *
 * ReadMode's contents panel scans for `<h2 id>`/`<h3 id>` only. A notebook whose markdown uses a
 * single `#` per section — the nbconvert norm, and what most authors write — produced `<h1>`s that
 * the panel could not see, so `countHeadings` counted them, `scaffold` stayed off, and the book
 * came out with NO navigable structure at all: exactly the unnavigable slab the scaffold branch
 * exists to prevent, reached by the opposite route. Demoting also removes a real duplication, since
 * the reader's masthead already prints the work's title above the body.
 *
 * h4–h6 keep their level (the panel ignores them either way) but still get ids, so in-page anchors
 * and deep links keep working.
 */
function withHeadingIds(html: string, used: Set<string>): string {
  return html.replace(/<h([1-6])([^>]*)>([\s\S]*?)<\/h\1>/gi, (m, lvl: string, attrs: string, inner: string) => {
    if (/\bid\s*=/.test(attrs)) return m;
    const label = inner.replace(/<[^>]+>/g, "").replace(/&[a-z]+;/gi, " ").trim();
    if (!label) return m;
    const out = lvl === "1" ? "2" : lvl;
    return `<h${out}${attrs} id="${uniqueId(slug(label), used)}">${inner}</h${out}>`;
  });
}

const MAX_BLOCK = 20_000;
const MAX_OUTPUT = 4_000;
const MAX_IMAGES = 40;

function clamp(s: string, max: number): string {
  if (s.length <= max) return s;
  return `${s.slice(0, max)}\n… ${(s.length - max).toLocaleString()} more characters not shown`;
}

/** ANSI SGR escapes, built from a code point so no control character sits in this source file. */
const ANSI = new RegExp(`${String.fromCharCode(27)}\\[[0-9;]*m`, "g");

const IMAGE_MIMES = ["image/png", "image/jpeg", "image/gif", "image/webp"];

/** `image/png` (etc.) output payloads are base64 WITHOUT the data: prefix. */
function dataUri(mime: string, payload: unknown): string {
  const b64 = joinSource(payload).replace(/\s+/g, "");
  if (!b64 || !/^[A-Za-z0-9+/=]+$/.test(b64)) return "";
  return `data:${mime};base64,${b64}`;
}

function codeBlock(text: string, lang: string, extraClass = ""): string {
  const cls = `aq-md-pre aq-nb-code${extraClass ? ` ${extraClass}` : ""}`;
  const label = lang ? ` data-lang="${esc(lang)}"` : "";
  return `<pre class="${cls}"${label}><code>${esc(tidy(text))}</code></pre>`;
}

/** Render one cell's outputs. Only fires for notebooks that carry them — a Kaggle pull does not. */
function renderOutputs(outputs: unknown[], images: BookImage[], step: number): string {
  const parts: string[] = [];
  for (const raw of outputs) {
    const o = (raw || {}) as Record<string, unknown>;
    const type = String(o.output_type || "");
    if (type === "stream") {
      const t = tidy(joinSource(o.text));
      if (t) parts.push(codeBlock(clamp(t, MAX_OUTPUT), "", "aq-nb-out"));
      continue;
    }
    if (type === "error") {
      const tb = (Array.isArray(o.traceback) ? o.traceback : [])
        .map((l) => String(l).replace(ANSI, "")) // a Jupyter traceback is ANSI-coloured
        .join("\n");
      const t = tidy(tb) || `${String(o.ename || "Error")}: ${String(o.evalue || "")}`;
      if (t.trim()) parts.push(codeBlock(clamp(t, MAX_OUTPUT), "", "aq-nb-out"));
      continue;
    }
    if (type === "execute_result" || type === "display_data") {
      const data = (o.data || {}) as Record<string, unknown>;
      const mime = IMAGE_MIMES.find((m) => data[m] !== undefined);
      if (mime && images.length < MAX_IMAGES) {
        const src = dataUri(mime, data[mime]);
        if (src) { images.push({ src, alt: `Output of step ${step}`, step }); continue; }
      }
      // text/html from a notebook is member-authored markup — never injected, shown as text.
      const t = tidy(joinSource(data["text/plain"]));
      if (t) parts.push(codeBlock(clamp(t, MAX_OUTPUT), "", "aq-nb-out"));
    }
  }
  return parts.join("\n");
}

/**
 * Build the book.
 *
 * Returns `null` when the payload is not a notebook we can read — the caller keeps the ordinary
 * work page rather than opening an empty reader, because a blank book is worse than no book.
 */
export function notebookToBook(raw: string | null | undefined): NotebookBook | null {
  const text = (raw || "").trim();
  if (!text) return null;

  let nb: Record<string, unknown>;
  try {
    nb = JSON.parse(text) as Record<string, unknown>;
  } catch {
    return null;
  }
  const cells = Array.isArray(nb.cells) ? (nb.cells as unknown[]) : null;
  if (!cells) return null;

  const meta = (nb.metadata || {}) as Record<string, unknown>;
  const kernelspec = (meta.kernelspec || {}) as Record<string, unknown>;
  const langInfo = (meta.language_info || {}) as Record<string, unknown>;
  const lang = String(kernelspec.language || langInfo.name || "python")
    .toLowerCase().replace(/[^a-z0-9+#-]/g, "").slice(0, 20) || "python";

  // Does the author's own markdown give the book structure? If it does, leave it completely alone:
  // an author who wrote headings has decided how their notebook reads, and a synthesised "Step 1"
  // between their sections fights them. Only a notebook with NO headings gets scaffolding, because
  // the contents panel is built from headings and without one the whole book is an unnavigable slab.
  let authorHeadings = 0;
  for (const c of cells) {
    const cell = (c || {}) as Record<string, unknown>;
    if (String(cell.cell_type) === "markdown") authorHeadings += countHeadings(joinSource(cell.source));
  }
  const scaffold = authorHeadings === 0;

  const images: BookImage[] = [];
  // Seeded with the ids ReadMode mints for its OWN contents rows. A notebook heading called
  // "Abstract" or "Figures" would otherwise take the id first and the panel's own entry would
  // scroll to the wrong element.
  const used = new Set<string>(["abstract", "figures"]);
  const out: string[] = [];
  let codeCells = 0;
  let mdCells = 0;
  let step = 0;

  for (const c of cells) {
    const cell = (c || {}) as Record<string, unknown>;
    const type = String(cell.cell_type || "");
    const source = tidy(joinSource(cell.source));

    if (type === "markdown") {
      if (!source) continue;
      mdCells++;
      out.push(withHeadingIds(renderRich(clamp(source, MAX_BLOCK)), used));
      continue;
    }
    if (type !== "code" || !source) continue;   // `raw` cells are directives, not prose
    codeCells++;
    step++;
    if (scaffold) {
      // Through uniqueId like every other heading: an author cell reading "## Step 1" (indented, so
      // countHeadings missed it and scaffold stayed on) would otherwise mint a second `step-1`, and
      // two elements with one id make the contents panel scroll to the wrong place — with duplicate
      // React keys for good measure.
      out.push(`<h2 class="aq-md-h" id="${uniqueId(`step-${step}`, used)}">Step ${step}</h2>`);
    }
    out.push(codeBlock(clamp(source, MAX_BLOCK), lang));

    const outs = Array.isArray(cell.outputs) ? (cell.outputs as unknown[]) : [];
    if (outs.length) {
      const rendered = renderOutputs(outs, images, step);
      if (rendered) out.push(rendered);
    }
  }

  if (!out.length) return null;

  return { html: out.join("\n"), lang, cells: cells.length, codeCells, mdCells, authorHeadings, images };
}

/** One-line description of what the book is made of, for the reader's byline. */
export function bookSummary(b: NotebookBook): string {
  const bits = [`${b.codeCells} code cell${b.codeCells === 1 ? "" : "s"}`];
  if (b.mdCells > 0) bits.push(`${b.mdCells} note${b.mdCells === 1 ? "" : "s"}`);
  return bits.join(" · ");
}
